using Stellar.Kernel.Quantization;

namespace Stellar.Kernel.Configuration
{
    /// <summary>
    /// Abstract base class for runtime configuration data passed to an entry point.
    /// </summary>
    /// <remarks>
    /// <para>This configuration contains metadata about the project (name, company, version) as well as
    /// a collection of <see cref="ConfigurationComponent"/> instances that provide module‑specific settings.</para>
    /// <para>Concrete implementations are generated by the Stellar build pipeline (S.R.I. builder).</para>
    /// </remarks>
    public abstract class RuntimeConfiguration
        : IQuantumObject
    {
        /// <summary>
        /// Gets or sets the name of the C# project.
        /// </summary>
        public string ProjectName { get; set; }

        /// <summary>
        /// Gets or sets the company name that created the project.
        /// </summary>
        public string CompanyName { get; set; }

        /// <summary>
        /// Gets or sets the project version string.
        /// </summary>
        public string Version { get; set; }

        /// <summary>
        /// Gets or sets the version of Stellar Orchester (the Stellar Software Kit).
        /// </summary>
        public string StellarOrchesterVersion { get; set; }

        /// <summary>
        /// Gets or sets the version of Stellar Engine.
        /// </summary>
        public string StellarEngineVersion { get; set; }

        /// <summary>
        /// Gets or sets the fully qualified name of the entry point class (derived from <see cref="EntryPoint.StellarEntryPoint"/>).
        /// </summary>
        public string EntryPoint { get; set; }

        /// <summary>
        /// Gets or sets the build date as a string (e.g., ISO 8601 format).
        /// </summary>
        public string BuildDate { get; set; }

        /// <summary>
        /// Gets or sets an array of configuration components that provide module‑specific settings.
        /// </summary>
        public ConfigurationComponent[] Components { get; set; }
    }
}