<Project Sdk="Stellar.Sdk/0.1.3">
    <PropertyGroup>
        <StellarSdkUsage>EngineModule</StellarSdkUsage>
        <IsPackable>true</IsPackable>
        <ModuleDescription>StellarEngine Assets pipeline runtime part</ModuleDescription>
    </PropertyGroup>
    <ItemGroup>
      <Folder Include="Build\Components\" />
    </ItemGroup>
</Project>
