<Project Sdk="Microsoft.NET.Sdk">
    <!-- Versions -->
    <Import Project="..\..\..\Data\version.props"/>

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;net9.0</TargetFrameworks>

        <Version>$(StellarKernelVersion)</Version>
        <AssemblyVersion>$(Version)</AssemblyVersion>

        <IsPackable>true</IsPackable>
        <Authors>QuantumDev</Authors>
        <PackageId>Stellar.Kernel</PackageId>
        <Description>StellarEngine base Kernel module</Description>
        <PackageVersion>$(Version)</PackageVersion>

        <RestoreLockedMode>false</RestoreLockedMode>
        <DisableImplicitFrameworkReferences>false</DisableImplicitFrameworkReferences>

        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <!-- Systems used only in runtime in net9.0-->
    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
        <Compile Remove="EventSystem\**\*.cs"/>
        <Compile Remove="TaskSystem\**\*.cs"/>
    </ItemGroup>
    <ItemGroup>
      <Folder Include="Label\" />
    </ItemGroup>
</Project>
