<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk"/>

    <!-- ========== DESIGN-TIME & BUILD-TIME ========== -->

    <!-- Validating -->
    <Target Name="StellarValidating"
            BeforeTargets="BeforeResolveReference"
            Condition="'$(StellarSdkUsage)' != 'Tests'">
        <Error Condition="'$(StellarSdkUsage)' == ''"
               Text="StellarSdkUsage must be configured!"/>

        <Error Condition="!Exists('$(StellarProjectConfigurationFile)')"
               Text="Config is not find in project files. Path: $(StellarProjectConfigurationFile)"/>

        <Message IsCritical="true"
                 Importance="high"
                 Text="=== STELLAR SDK: $(StellarProjectName) is valid StellarProject ==="/>
    </Target>

    <!-- Parsing configurations -->
    <UsingTask TaskName="Stellar.Sdk.Tasks.StellarConfigParser"
               AssemblyFile="../build/Stellar.Sdk.Tasks.dll"/>
    <Target Name="StellarParseConfigurations"
            BeforeTargets="Build;AssignTargetPaths;PrepareForBuild"
            DependsOnTargets="StellarValidating"
            Condition="'$(StellarSdkUsage)' != 'Tests'">
        <Message IsCritical="true" Importance="high" Text="=== STELLAR SDK: Configuration parsing ==="/>

        <StellarConfigParser
                ProjectDirectory="$(MSBuildProjectDirectory)"
                StellarProjectName="$(StellarProjectName)"
                StellarProjectConfigurationFile="$(StellarProjectConfigurationFile)"
                StellarLocalizationIndexType="$(StellarLocalizationIndexType)">
            <Output TaskParameter="Assets" ItemName="StellarAssets"/>
            <Output TaskParameter="EmbeddedAssets" ItemName="StellarEmbeddedAssets"/>

            <Output TaskParameter="DefaultCulture" ItemName="StellarDefaultCulture"/>
            <Output TaskParameter="SupportedCultures" ItemName="StellarSupportedCultures"/>
            <Output TaskParameter="LocalizationIndexFiles" ItemName="StellarLocalizationIndexFiles"/>
        </StellarConfigParser>

        <ItemGroup>
            <!-- Assets -->
            <Content Include="@(StellarAssets)"/>
            <EmbeddedResource Include="@(StellarEmbeddedAssets)"/>

            <!-- Localization -->
            <Content Include="@(StellarLocalizationIndexFiles)"
                     Condition="'$(StellarLocalizationIndexType)' == 'External'"/>
            <EmbeddedResource Include="@(StellarLocalizationIndexFiles)"
                              Condition="'$(StellarLocalizationIndexType)' == 'Embedded'"/>
        </ItemGroup>
    </Target>

    <!-- Parsing .csproj file -->
    <UsingTask TaskName="Stellar.Sdk.Tasks.StellarParseCSProjectFile"
               AssemblyFile="../build/Stellar.Sdk.Tasks.dll"/>
    <Target Name="StellarParseCsProject"
            BeforeTargets="Build;CollectPackageReferences;ResolveProjectReferencesDesignTime2"
            DependsOnTargets="StellarValidating">
        <Message IsCritical="true" Importance="high" Text="=== STELLAR SDK: CSProj parsing ==="/>

        <StellarParseCSProjectFile
                ProjectFile="$(MSBuildProjectFullPath)"
                StellarPrecompiled="$(StellarPrecompiled)"
                StellarEngineVersion="$(StellarEngineVersion)"
                StellarOrchesterInstallationDir="$(StellarOrchesterInstallationDir)">
            <Output TaskParameter="StellarDependenciesAsProject" ItemName="StellarDependenciesAsProject"/>
            <Output TaskParameter="StellarDependenciesAsPackages" ItemName="StellarDependenciesAsPackages"/>
        </StellarParseCSProjectFile>
    </Target>

    <!-- Applying dependency modules -->
    <Target Name="StellarDependenciesApply"
            BeforeTargets="Build;ResolveProjectReferencesDesignTime2;ResolvePackageDependenciesDesignTime"
            DependsOnTargets="StellarParseCsProject">
        <ItemGroup>
            <ProjectReference Include="@(StellarDependenciesAsProject)"/>
            <PackageReference Include="@(StellarDependenciesAsPackages)"/>
        </ItemGroup>
    </Target>

    <!-- ========== BUILD-TIME ONLY ========== -->

    <!-- Entry Point -->
    <UsingTask TaskName="Stellar.Sdk.Tasks.StellarEntryPointFind"
               AssemblyFile="../build/Stellar.Sdk.Tasks.dll"/>
    <Target Name="StellarFindEntryPoint"
            BeforeTargets="CoreCompile"
            Condition="'$(StellarSdkUsage)' != 'Tests'">
        <Message IsCritical="true" Importance="high" Text="=== STELLAR SDK: Searching entry point ==="/>

        <StellarEntryPointFind
                CompileItems="@(Compile)"
                ProjectDirectory="$(MSBuildProjectDirectory)">
            <Output TaskParameter="StellarEntryPoint" ItemName="StellarEntryPoint"/>
        </StellarEntryPointFind>
    </Target>

    <!-- Generating Runtime Configuration -->
    <UsingTask TaskName="Stellar.Sdk.Tasks.StellarConfigGenerator"
               AssemblyFile="../build/Stellar.Sdk.Tasks.dll"/>
    <Target Name="StellarGenerateRuntimeConfig"
            BeforeTargets="Build"
            DependsOnTargets="StellarParseConfigurations;StellarFindEntryPoint">
        <Message IsCritical="true" Importance="high" Text="=== STELLAR SDK: Configuration files generating ==="/>

        <StellarConfigGenerator
                IntermediateOutputPath="$(IntermediateOutputPath)"
                StellarRuntimeConfigType="$(StellarRuntimeConfigType)"

                StellarProjectName="$(StellarProjectName)"
                CompanyName="$(CompanyName)"
                Version="$(Version)"
                StellarOrchesterVersion="$(StellarOrchesterVersion)"
                StellarEngineVersion="$(StellarEngineVersion)"
                StellarEntryPoint="@(StellarEntryPoint)"

                StellarAssets="@(StellarAssets)"
                StellarEmbeddedAssets="@(StellarEmbeddedAssets)"

                StellarDefaultCulture="@(StellarDefaultCulture)"
                StellarSupportedCultures="@(StellarSupportedCultures)"
                StellarLocalizationIndexFiles="@(StellarLocalizationIndexFiles)">
            <Output TaskParameter="StellarRuntimeConfigFile" ItemName="StellarRuntimeConfigFile"/>
        </StellarConfigGenerator>

        <ItemGroup>
            <Content Include="@(StellarRuntimeConfigFile)"
                     Condition="'$(StellarRuntimeConfigType)' == 'External'"/>
            <EmbeddedResource Include="@(StellarRuntimeConfigFile)"
                              Condition="'$(StellarRuntimeConfigType)' == 'Embedded'"/>
        </ItemGroup>
    </Target>

    <!-- Generation assembly info -->
    <Target Name="StellarGenerateAssemblyInfoAttributes"
            BeforeTargets="CoreCompile"
            Condition="'$(StellarSdkUsage)' != 'Tests'">
        <Message IsCritical="true" Importance="high" Text="=== STELLAR SDK: AssemblyInfo generation ==="/>

        <WriteLinesToFile
                File="$(IntermediateOutputPath)Stellar.AssemblyInfo.g.cs"
                Lines="//------------------------------------------------------------------------------
// This code automatically generated by Stellar.Tools build
//------------------------------------------------------------------------------

using System.Reflection%3B
[assembly: AssemblyMetadata(&quot;StellarOrchesterVersion&quot;, &quot;$(StellarOrchesterVersion)&quot;)]
[assembly: AssemblyMetadata(&quot;StellarRuntimeConfigType&quot;, &quot;$(StellarRuntimeConfigType)&quot;)]
"
                Overwrite="true"/>

        <ItemGroup>
            <Compile Include="$(IntermediateOutputPath)Stellar.AssemblyInfo.g.cs"/>
        </ItemGroup>
    </Target>

    <!-- Generation executable -->
    <UsingTask TaskName="Stellar.Sdk.Tasks.StellarExecutableGenerator"
               AssemblyFile="../build/Stellar.Sdk.Tasks.dll"/>
    <Target Name="StellarGenerateExecutable"
            AfterTargets="Build"
            DependsOnTargets="StellarFindEntryPoint"
            Condition="'$(StellarSdkUsage)' == 'ExecutableModule'">
        <Message IsCritical="true" Importance="high" Text="=== STELLAR SDK: Executable generation for ExecutableModule ==="/>

        <StellarExecutableGenerator
                ProjectDirectory="$(MSBuildProjectDirectory)"
                OutputPath="$(OutputPath)"
                RunConfiguration="$(Configuration)"

                StellarProjectName="$(StellarProjectName)"
                StellarOutputType="$(StellarOutputType)"
                StellarOrchesterInstallationDir="$(StellarOrchesterInstallationDir)"/>
    </Target>
</Project>