<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk"/>

    <!-- Base .NET -->
    <PropertyGroup>
        <WinSdkVersion Condition="'$(WinSdkVersion)' == ''">10.0.26100.0</WinSdkVersion>
        <TargetFramework Condition="'$(TargetFramework)' == ''">net9.0-windows$(WinSdkVersion)</TargetFramework>
        <OutputType Condition="'$(OutputType)' == ''">Library</OutputType>

        <!-- Plantform and runtime -->
        <PlatformTarget>x64</PlatformTarget>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>

        <!-- build configuration -->
        <Configurations>Debug;Release</Configurations>
        <Platforms>x64</Platforms>

        <!-- Build path configuration -->
        <OutputPath>bin/$(Configuration)</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    </PropertyGroup>

    <!-- Stellar Configurations -->
    <PropertyGroup>
        <StellarPrecompiled Condition="'$(StellarPrecompiled)' == ''">false</StellarPrecompiled>
        <StellarOutputType Condition="'$(StellarOutputType)' == ''">Modern</StellarOutputType>
        <StellarProjectName Condition="'$(StellarProjectName)' == ''">$(AssemblyName)</StellarProjectName>
        <CompanyName Condition="'$(CompanyName)' == ''">Unknown</CompanyName>

        <StellarVersionFile Condition="'$(StellarVersionFile)' == ''">$(StellarProjectName).stellar.version.txt</StellarVersionFile>
        <StellarProjectConfigurationFile Condition="'$(StellarProjectConfigurationFile)' == ''">$(StellarProjectName).stellar.project</StellarProjectConfigurationFile>

        <StellarRuntimeConfigType Condition="'$(StellarRuntimeConfigType)' == ''">External</StellarRuntimeConfigType>
        <StellarLocalizationIndexType Condition="'$(StellarLocalizationIndexType)' == ''">External</StellarLocalizationIndexType>
    </PropertyGroup>

    <!-- Versions -->
    <Import Project="version.props" Condition="'$(StellarOrchesterVersion)' == ''"/>

    <!-- Stellar Directories -->
    <PropertyGroup>
        <_StellarSharedDirPathVar>$([System.Environment]::GetEnvironmentVariable('STELLAR_SHARED_DIR'))</_StellarSharedDirPathVar>
    </PropertyGroup>
    <!-- From Path var -->
    <PropertyGroup Condition="'$(_StellarSharedDirPathVar)' != ''">
        <StellarOrchesterSharedDir>$(_StellarSharedDirPathVar)/$(StellarOrchesterVersion)</StellarOrchesterSharedDir>
    </PropertyGroup>
    <!-- From Home directory -->
    <PropertyGroup Condition="'$(_StellarSharedDirPathVar)' == ''">
        <_HomeDirectory Condition="'$(OS)' == 'Windows_NT'">$(USERPROFILE)</_HomeDirectory>
        <_HomeDirectory Condition="'$(OS)' != 'Windows_NT'">$(HOME)</_HomeDirectory>
    </PropertyGroup>
    <PropertyGroup Condition="'$(_HomeDirectory)' != ''">
        <StellarOrchesterSharedDir>$(_HomeDirectory)/.stellar/$(StellarOrchesterVersion)</StellarOrchesterSharedDir>
    </PropertyGroup>
    <!-- Installation -->
    <PropertyGroup Condition="'$(StellarOrchesterSharedDir)' != ''">
        <_StellarOrchesterInstallationFile>$(StellarOrchesterSharedDir)/installation_location.txt</_StellarOrchesterInstallationFile>
    </PropertyGroup>
    <PropertyGroup Condition="'$(_StellarOrchesterInstallationFile)' != '' and Exists('$(_StellarOrchesterInstallationFile)')">
        <StellarOrchesterInstallationDir>$([System.IO.File]::ReadAllText('$(_StellarOrchesterInstallationFile)').Trim())</StellarOrchesterInstallationDir>
    </PropertyGroup>

    <!-- Stellar Configurations fot different project types -->
    <Import Project="StellarUsageDefinations.props"/>
</Project>