<Project>
    <!-- Versions -->
    <Import Project="version.props" Condition="'$(StellarOrchesterVersion)' == ''"/>

    <!-- StellarSdkUsage - Tests -->
    <PropertyGroup Condition="'$(StellarSdkUsage)' == 'Tests'">
        <CompanyName>QuantumDev</CompanyName>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>
    <ItemGroup Condition="'$(StellarSdkUsage)' == 'Tests'">
        <PackageReference Include="coverlet.collector" Version="6.0.2"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0"/>

        <PackageReference Include="xunit" Version="2.9.2"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2"/>

        <PackageReference Include="FluentAssertions" Version="6.12.0"/>
        <PackageReference Include="Moq" Version="4.20.69"/>
    </ItemGroup>
    <ItemGroup Condition="'$(StellarSdkUsage)' == 'Tests'">
        <Using Include="Xunit"/>
        <Using Include="FluentAssertions"/>
        <Using Include="Moq"/>
    </ItemGroup>

    <ItemGroup Condition="'$(StellarSdkUsage)' != 'Tests'">
        <Analyzer Include="$(StellarOrchesterInstallationDir)/SDK/src/Stellar.ProjectAnalyzer/bin/Debug/netstandard2.0/Stellar.ProjectAnalyzer.dll"/>
    </ItemGroup>

    <!-- StellarSdkUsage - ExecutableModule -->
    <PropertyGroup Condition="'$(StellarSdkUsage)' == 'ExecutableModule'">
        <StellarGameIcon Condition="'$(StellarGameIcon)' == ''">$(StellarProjectName).ico</StellarGameIcon>
        <StellarGameManifest Condition="'$(StellarGameManifest)' == ''">$(StellarProjectName).manifest</StellarGameManifest>

        <ApplicationIcon Condition="Exists('$(StellarGameIcon)')">$(StellarGameIcon)</ApplicationIcon>
        <ApplicationManifest Condition="Exists('$(StellarGameManifest)')">$(StellarGameManifest)</ApplicationManifest>
    </PropertyGroup>
    <ItemGroup Condition="'$(StellarSdkUsage)' == 'ExecutableModule' and '$(StellarPrecompiled)' == 'false'">
        <ProjectReference Include="$(StellarOrchesterInstallationDir)/Engine/src/Stellar.Engine/Stellar.Engine.csproj"/>
    </ItemGroup>
    <ItemGroup Condition="'$(StellarSdkUsage)' == 'ExecutableModule' and '$(StellarPrecompiled)' == 'true'">
        <PackageReference Include="Stellar.Engine" Version="[$(StellarEngineVersion)]"/>
    </ItemGroup>

    <!-- StellarSdkUsage - Module -->
    <PropertyGroup Condition="'$(StellarSdkUsage)' == 'Module'">
    </PropertyGroup>
    <ItemGroup Condition="'$(StellarSdkUsage)' == 'Module' and '$(StellarPrecompiled)' == 'false'">
        <ProjectReference Include="$(StellarOrchesterInstallationDir)/Engine/src/Stellar.Engine/Stellar.Engine.csproj"/>
        <ProjectReference Include="$(StellarOrchesterInstallationDir)/Kernel/src/Stellar.Kernel/Stellar.Kernel.csproj" PrivateAssets="all"/>
    </ItemGroup>
    <ItemGroup Condition="'$(StellarSdkUsage)' == 'Module' and '$(StellarPrecompiled)' == 'true'">
        <PackageReference Include="Stellar.Engine" Version="[$(StellarEngineVersion)]"/>
        <PackageReference Include="Stellar.Kernel" Version="[$(StellarKernelVersion)]" PrivateAssets="all"/>
    </ItemGroup>

    <!-- StellarSdkUsage - Engine Modules Base propertyes -->
    <PropertyGroup Condition="'$(StellarSdkUsage)' == 'EngineModule' or '$(StellarSdkUsage)' == 'EngineCoreModule'">
        <CompanyName>QuantumDev</CompanyName>

        <Version>$(StellarEngineVersion)</Version>
        <AssemblyVersion>$(Version)</AssemblyVersion>
    </PropertyGroup>

    <!-- StellarSdkUsage - EngineModule -->
    <PropertyGroup Condition="'$(StellarSdkUsage)' == 'EngineModule'">
    </PropertyGroup>
    <ItemGroup Condition="'$(StellarSdkUsage)' == 'EngineModule' and '$(StellarPrecompiled)' == 'false'">
        <ProjectReference Include="$(StellarOrchesterInstallationDir)/Kernel/src/Stellar.Kernel/Stellar.Kernel.csproj" PrivateAssets="all"/>
        <ProjectReference Include="$(StellarOrchesterInstallationDir)/Engine/src/Modules/Stellar.Core/Stellar.Core.csproj" PrivateAssets="all"/>
    </ItemGroup>
    <ItemGroup Condition="'$(StellarSdkUsage)' == 'EngineModule' and '$(StellarPrecompiled)' == 'true'">
        <PackageReference Include="Stellar.Kernel" Version="[$(StellarKernelVersion)]" PrivateAssets="all"/>
        <PackageReference Include="Stellar.Core" Version="[$(StellarEngineVersion)]" PrivateAssets="all"/>
    </ItemGroup>

    <!-- StellarSdkUsage - EngineCoreModule -->
    <PropertyGroup Condition="'$(StellarSdkUsage)' == 'EngineCoreModule'">
    </PropertyGroup>
    <ItemGroup Condition="'$(StellarSdkUsage)' == 'EngineCoreModule' and '$(StellarPrecompiled)' == 'false'">
        <ProjectReference Include="$(StellarOrchesterInstallationDir)/Kernel/src/Stellar.Kernel/Stellar.Kernel.csproj" PrivateAssets="all"/>
    </ItemGroup>
    <ItemGroup Condition="'$(StellarSdkUsage)' == 'EngineCoreModule' and '$(StellarPrecompiled)' == 'true'">
        <PackageReference Include="Stellar.Kernel" Version="[$(StellarKernelVersion)]" PrivateAssets="all"/>
    </ItemGroup>

    <!-- Package information -->
    <PropertyGroup Condition="'$(IsPackable)' == 'true'">
        <Authors Condition="'$(Authors)' == ''">$(CompanyName)</Authors>
        <PackageId Condition="'$(PackageId)' == ''">$(StellarProjectName)</PackageId>
        <Description Condition="'$(Description)' == ''">$(ModuleDescription)</Description>
        <PackageVersion Condition="'$(PackageVersion)' == ''">$(Version)</PackageVersion>
    </PropertyGroup>
</Project>