<Project Sdk="Stellar.Sdk/0.2.0">
    <PropertyGroup>
        <StellarSdkUsage>EngineModule</StellarSdkUsage>
        <IsPackable>true</IsPackable>
        <ModuleDescription>StellarEngine Logging module</ModuleDescription>

        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ProjectExtensions>
        <StellarDependency Include="Stellar.FileSystem" Type="EngineModule"/>
    </ProjectExtensions>
</Project>
