<Project Sdk="Stellar.Sdk/0.1.2">
    <PropertyGroup>
        <StellarSdkUsage>EngineModule</StellarSdkUsage>
        <IsPackable>true</IsPackable>
        <ModuleDescription>StellarEngine Logging module</ModuleDescription>

        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <StellarDependency Type="EngineModule" AllowPrecompiled="true" Include="Stellar.FileSystem"/>
    </ItemGroup>
</Project>
