<Project Sdk="Stellar.Sdk/0.1.3">
    <PropertyGroup>
        <StellarSdkUsage>EngineModule</StellarSdkUsage>
        <IsPackable>true</IsPackable>
        <ModuleDescription>StellarEngine Logging module</ModuleDescription>

        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <!-- TODO: Implement StellarDependency tag -->
        <!--<StellarDependency Type="EngineModule" AllowPrecompiled="true" Include="Stellar.FileSystem"/>-->
    </ItemGroup>

    <ItemGroup Condition="$(StellarPrecompiled) == 'false'">
        <ProjectReference Include="$(StellarOrchesterInstallationDir)/Engine/src/Modules/Stellar.FileSystem/Stellar.FileSystem.csproj"/>
    </ItemGroup>
    <ItemGroup Condition="$(StellarPrecompiled) == 'true'">
        <PackageReference Include="Stellar.FileSystem" Version="$(StellarEngineVersion)"/>
    </ItemGroup>
</Project>
