<Project Sdk="Stellar.Sdk/0.2.0">
    <PropertyGroup>
        <StellarSdkUsage>Tests</StellarSdkUsage>
        
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="$(StellarOrchesterInstallationDir)/Engine/src/Modules/Stellar.Core/Stellar.Core.csproj"/>
        <ProjectReference Include="$(StellarOrchesterInstallationDir)/Kernel/src/Stellar.Kernel/Stellar.Kernel.csproj"/>
    </ItemGroup>
</Project>
