<Project Sdk="Stellar.Sdk/0.1.3">
    <PropertyGroup>
        <StellarSdkUsage>EngineModule</StellarSdkUsage>
        <IsPackable>true</IsPackable>
        <ModuleDescription>StellarEngine abstract FileSystem</ModuleDescription>

        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
</Project>
