<Project Sdk="Stellar.Sdk/0.2.0">
    <PropertyGroup>
        <StellarSdkUsage>EngineCoreModule</StellarSdkUsage>
        <IsPackable>true</IsPackable>
        <ModuleDescription>StellarEngine Core</ModuleDescription>

        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
</Project>
