<Project Sdk="Stellar.Sdk/0.1.2">
    <PropertyGroup>
        <StellarSdkUsage>EngineCoreModule</StellarSdkUsage>
        <IsPackable>true</IsPackable>
        <ModuleDescription>StellarEngine Core module</ModuleDescription>

        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
</Project>
