<Project Sdk="Stellar.Sdk/0.1.1">
    <PropertyGroup>
        <StellarSdkUsage>EngineModule</StellarSdkUsage>
        <CompanyName>QuantumDev</CompanyName>

        <Version>$(StellarEngineVersion)</Version>
        <AssemblyVersion>$(Version)</AssemblyVersion>

        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <!-- Package props -->
    <PropertyGroup>
        <IsPackable>true</IsPackable>
        <Authors>$(CompanyName)</Authors>
        <PackageId>Stellar.Graphic</PackageId>
        <Description>StellarEngine Graphic module</Description>
        <PackageVersion>$(Version)</PackageVersion>
    </PropertyGroup>
</Project>
